{% set name = "PyAEZ" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa796d25d5ebf91f64d018cfc56fa617dfd56347edde526df352b0cf62e88e71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pip
    - numpy
    - numba
    - scipy
    - gdal
    - pandas

test:
  imports:
    - pyaez
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/gicait/pyaez
  summary: PyAEZ is a python package consisted of many algorithms related to Agro-ecalogical zoning (AEZ) framework.
  description: |
    PyAEZ is a python package consisted of many algorithms related to Agro-ecalogical zoning (AEZ) framework. PyAEZ tries to encapsulate all complex calculations in AEZ and try to provide user friendly, and intuitive ways to input data and output results after calculations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/gicait/pyaez/docs
  dev_url: https://github.com/gicait/pyaez

extra:
  recipe-maintainers:
    - iamtekson
    - kboonma
