{% set name = "PyAEZ" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6f9c4f4ad33b64d98bf6a0966a688c6dceae227e292f8bcb78aaf42b023f987

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - numpy
    - numba
    - scipy
    - gdal
    - pandas

test:
  imports:
    - pyaez
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/gicait/pyaez
  summary: PyAEZ is a python package consisted of many algorithms related to Agro-ecalogical zoning (AEZ) framework.
  description: |
    PyAEZ is a python package consisted of many algorithms related to Agro-ecalogical zoning (AEZ) framework. PyAEZ tries to encapsulate all complex calculations in AEZ and try to provide user friendly, and intuitive ways to input data and output results after calculations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/gicait/pyaez/docs
  dev_url: https://github.com/gicait/pyaez

extra:
  recipe-maintainers:
    - iamtekson
    - kboonma
